# Generated by Django 6.0.1 on 2026-05-24 07:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(default='kmeans', max_length=50, unique=True)),
                ('api_key', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'AI Config',
            },
        ),
        migrations.CreateModel(
            name='ClusterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_referensi', models.CharField(blank=True, max_length=50, null=True)),
                ('umur', models.IntegerField()),
                ('tkp', models.CharField(max_length=255)),
                ('penyebab', models.CharField(max_length=255)),
                ('hari', models.CharField(max_length=20)),
                ('tanggal', models.DateField()),
                ('jam', models.CharField(max_length=10)),
                ('jenis_kendaraan', models.CharField(max_length=100)),
                ('tipe_kendaraan', models.CharField(max_length=100)),
                ('kerugian_material', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Cluster Data',
                'db_table': 'clusterdata',
                'ordering': ['-tanggal', '-jam'],
            },
        ),
        migrations.CreateModel(
            name='Kecamatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KecelakaanRaw',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nomor_kecelakaan', models.CharField(blank=True, help_text='Nomor identitas kecelakaan', max_length=50, null=True)),
                ('tanggal', models.DateField()),
                ('waktu', models.TimeField()),
                ('latitude', models.DecimalField(decimal_places=20, max_digits=30)),
                ('longitude', models.DecimalField(decimal_places=20, max_digits=30)),
                ('korban_meninggal', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('korban_luka_berat', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('korban_luka_ringan', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('kerugian_materi', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('desa', models.CharField(max_length=100)),
                ('kecamatan', models.CharField(max_length=100)),
                ('kabupaten_kota', models.CharField(max_length=100)),
                ('keterangan', models.TextField(blank=True)),
                ('polres', models.CharField(choices=[('madiun', 'Polres Madiun'), ('madiun_kota', 'Polres Madiun Kota')], default='madiun', help_text='Polres yang upload data raw ini', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Data Kecelakaan Raw',
                'ordering': ['-tanggal', '-waktu'],
            },
        ),
        migrations.CreateModel(
            name='Kota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RuasJalan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama_ruas', models.CharField(max_length=100)),
                ('jenis_jalan', models.CharField(choices=[('tol', 'Jalan Tol'), ('arteri', 'Jalan Arteri'), ('kolektor', 'Jalan Kolektor'), ('lokal', 'Jalan Lokal'), ('desa', 'Jalan Desa')], max_length=20)),
                ('wilayah', models.CharField(max_length=100)),
                ('panjang_km', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('lat_awal', models.DecimalField(blank=True, decimal_places=20, help_text='Latitude titik awal ruas jalan', max_digits=25, null=True)),
                ('lon_awal', models.DecimalField(blank=True, decimal_places=20, help_text='Longitude titik awal ruas jalan', max_digits=25, null=True)),
                ('lat_akhir', models.DecimalField(blank=True, decimal_places=20, help_text='Latitude titik akhir ruas jalan', max_digits=25, null=True)),
                ('lon_akhir', models.DecimalField(blank=True, decimal_places=20, help_text='Longitude titik akhir ruas jalan', max_digits=25, null=True)),
                ('geometry', models.TextField(blank=True, help_text='GeoJSON LineString untuk seluruh ruas jalan', null=True)),
                ('polres', models.CharField(choices=[('madiun', 'Polres Madiun'), ('madiun_kota', 'Polres Madiun Kota')], default='madiun', help_text='Polres yang menambahkan ruas jalan ini', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Ruas Jalan',
                'ordering': ['nama_ruas'],
            },
        ),
        migrations.CreateModel(
            name='Kelurahan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kecamatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.kecamatan')),
            ],
        ),
        migrations.AddField(
            model_name='kecamatan',
            name='kota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.kota'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polres', models.CharField(choices=[('madiun', 'Polres Madiun'), ('madiun_kota', 'Polres Madiun Kota')], default='madiun', help_text='Polres yang dikelola oleh user ini', max_length=20)),
                ('alamat', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SegmenJalan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('km_awal', models.DecimalField(decimal_places=3, max_digits=10)),
                ('km_akhir', models.DecimalField(decimal_places=3, max_digits=10)),
                ('panjang_segmen', models.DecimalField(decimal_places=3, max_digits=10)),
                ('lat_awal', models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True)),
                ('lon_awal', models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True)),
                ('lat_akhir', models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True)),
                ('lon_akhir', models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True)),
                ('titik_awal', models.CharField(blank=True, help_text='Label titik awal (contoh: Titik 1)', max_length=100, null=True)),
                ('titik_akhir', models.CharField(blank=True, help_text='Label titik akhir (contoh: Titik 2)', max_length=100, null=True)),
                ('nama_segmen', models.CharField(blank=True, help_text='Nama segmen, bisa diubah dinamis', max_length=255, null=True)),
                ('keterangan', models.TextField(blank=True, help_text='Penjelasan/keterangan segmen', null=True)),
                ('geometry', models.TextField(blank=True, help_text='GeoJSON LineString untuk segmen ini', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ruas_jalan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmen_jalan', to='coreapp.ruasjalan')),
            ],
            options={
                'verbose_name_plural': 'Segmen Jalan',
                'ordering': ['ruas_jalan', 'km_awal'],
                'unique_together': {('ruas_jalan', 'km_awal', 'km_akhir')},
            },
        ),
        migrations.CreateModel(
            name='KecelakaanPreprosesing',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nomor_kecelakaan', models.CharField(blank=True, help_text='Nomor identitas kecelakaan', max_length=50, null=True)),
                ('tanggal', models.DateField()),
                ('waktu', models.TimeField()),
                ('latitude', models.DecimalField(decimal_places=20, max_digits=30)),
                ('longitude', models.DecimalField(decimal_places=20, max_digits=30)),
                ('korban_meninggal', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('korban_luka_berat', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('korban_luka_ringan', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('kerugian_materi', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('desa', models.CharField(max_length=100)),
                ('kecamatan', models.CharField(max_length=100)),
                ('kabupaten_kota', models.CharField(max_length=100)),
                ('keterangan', models.TextField(blank=True)),
                ('polres', models.CharField(choices=[('madiun', 'Polres Madiun'), ('madiun_kota', 'Polres Madiun Kota')], default='madiun', help_text='Polres yang upload data preprocessing ini', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('segmen_jalan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kecelakaan_preprosesing', to='coreapp.segmenjalan')),
            ],
            options={
                'verbose_name_plural': 'Data Kecelakaan Preprocessing',
                'ordering': ['-tanggal', '-waktu'],
            },
        ),
        migrations.CreateModel(
            name='Kecelakaan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('waktu', models.TimeField()),
                ('latitude', models.DecimalField(decimal_places=20, help_text='Latitude koordinat kecelakaan', max_digits=30)),
                ('longitude', models.DecimalField(decimal_places=20, help_text='Longitude koordinat kecelakaan', max_digits=30)),
                ('korban_meninggal', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('korban_luka_berat', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('korban_luka_ringan', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('kerugian_materi', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('desa', models.CharField(max_length=100)),
                ('kecamatan', models.CharField(max_length=100)),
                ('kabupaten_kota', models.CharField(max_length=100)),
                ('keterangan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('segmen_jalan', models.ForeignKey(blank=True, help_text='Otomatis diassign ke segmen terdekat (threshold 5km) saat disimpan. Bisa diubah manual jika perlu.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kecelakaan', to='coreapp.segmenjalan')),
            ],
            options={
                'verbose_name_plural': 'Kecelakaan',
                'ordering': ['-tanggal', '-waktu'],
            },
        ),
        migrations.CreateModel(
            name='RekapSegmen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jumlah_kecelakaan', models.IntegerField(default=0)),
                ('total_korban', models.IntegerField(default=0)),
                ('total_meninggal', models.IntegerField(default=0)),
                ('total_luka_berat', models.IntegerField(default=0)),
                ('total_luka_ringan', models.IntegerField(default=0)),
                ('total_kerugian', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('periode_tahun', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('segmen_jalan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rekap', to='coreapp.segmenjalan')),
            ],
            options={
                'verbose_name_plural': 'Rekap Segmen',
                'ordering': ['-periode_tahun', 'segmen_jalan'],
                'unique_together': {('segmen_jalan', 'periode_tahun')},
            },
        ),
        migrations.CreateModel(
            name='AnalisisZScore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nilai_zscore', models.DecimalField(decimal_places=3, max_digits=5)),
                ('kategori', models.CharField(choices=[('sangat_tinggi', 'Sangat Tinggi (Z > 1.5)'), ('tinggi', 'Tinggi (0.5 < Z ≤ 1.5)'), ('sedang', 'Sedang (-0.5 < Z ≤ 0.5)'), ('rendah', 'Rendah (-1.5 < Z ≤ -0.5)'), ('sangat_rendah', 'Sangat Rendah (Z ≤ -1.5)')], max_length=20)),
                ('tahun', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('segmen_jalan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_zscore', to='coreapp.segmenjalan')),
            ],
            options={
                'verbose_name_plural': 'Analisis Z-Score',
                'ordering': ['-tahun', '-nilai_zscore'],
                'unique_together': {('segmen_jalan', 'tahun')},
            },
        ),
    ]
