# Generated by Django 6.0.1 on 2026-01-25 13:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RuasJalan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama_ruas', models.CharField(max_length=100)),
                ('jenis_jalan', models.CharField(choices=[('tol', 'Jalan Tol'), ('arteri', 'Jalan Arteri'), ('kolektor', 'Jalan Kolektor'), ('lokal', 'Jalan Lokal'), ('desa', 'Jalan Desa')], max_length=20)),
                ('wilayah', models.CharField(max_length=100)),
                ('panjang_km', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Ruas Jalan',
                'ordering': ['nama_ruas'],
            },
        ),
        migrations.CreateModel(
            name='SegmenJalan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('km_awal', models.DecimalField(decimal_places=3, max_digits=10)),
                ('km_akhir', models.DecimalField(decimal_places=3, max_digits=10)),
                ('panjang_segmen', models.DecimalField(decimal_places=3, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ruas_jalan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmen_jalan', to='coreapp.ruasjalan')),
            ],
            options={
                'verbose_name_plural': 'Segmen Jalan',
                'ordering': ['ruas_jalan', 'km_awal'],
                'unique_together': {('ruas_jalan', 'km_awal', 'km_akhir')},
            },
        ),
        migrations.CreateModel(
            name='Kecelakaan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('waktu', models.TimeField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('jumlah_kecelakaan', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('korban_meninggal', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('korban_luka_berat', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('korban_luka_ringan', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('kerugian_materi', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('desa', models.CharField(max_length=100)),
                ('kecamatan', models.CharField(max_length=100)),
                ('kabupaten_kota', models.CharField(max_length=100)),
                ('keterangan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('segmen_jalan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kecelakaan', to='coreapp.segmenjalan')),
            ],
            options={
                'verbose_name_plural': 'Kecelakaan',
                'ordering': ['-tanggal', '-waktu'],
            },
        ),
        migrations.CreateModel(
            name='RekapSegmen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jumlah_kecelakaan', models.IntegerField(default=0)),
                ('total_korban', models.IntegerField(default=0)),
                ('total_meninggal', models.IntegerField(default=0)),
                ('total_luka_berat', models.IntegerField(default=0)),
                ('total_luka_ringan', models.IntegerField(default=0)),
                ('total_kerugian', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('periode_tahun', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('segmen_jalan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rekap', to='coreapp.segmenjalan')),
            ],
            options={
                'verbose_name_plural': 'Rekap Segmen',
                'ordering': ['-periode_tahun', 'segmen_jalan'],
                'unique_together': {('segmen_jalan', 'periode_tahun')},
            },
        ),
        migrations.CreateModel(
            name='AnalisisZScore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nilai_zscore', models.DecimalField(decimal_places=3, max_digits=5)),
                ('kategori', models.CharField(choices=[('sangat_tinggi', 'Sangat Tinggi (Z > 1.5)'), ('tinggi', 'Tinggi (0.5 < Z ≤ 1.5)'), ('sedang', 'Sedang (-0.5 < Z ≤ 0.5)'), ('rendah', 'Rendah (-1.5 < Z ≤ -0.5)'), ('sangat_rendah', 'Sangat Rendah (Z ≤ -1.5)')], max_length=20)),
                ('tahun', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('segmen_jalan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_zscore', to='coreapp.segmenjalan')),
            ],
            options={
                'verbose_name_plural': 'Analisis Z-Score',
                'ordering': ['-tahun', '-nilai_zscore'],
                'unique_together': {('segmen_jalan', 'tahun')},
            },
        ),
    ]
