# Generated by Django 6.0.1 on 2026-05-24 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Polres')),
                ('kode', models.CharField(help_text='Contoh: polres_madiun', max_length=50, unique=True, verbose_name='Kode Polres')),
                ('alamat', models.TextField(blank=True, null=True, verbose_name='Alamat')),
                ('telepon', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telepon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Polres',
                'verbose_name_plural': 'Polres',
                'ordering': ['nama'],
            },
        ),
        migrations.AlterField(
            model_name='kecelakaanpreprosesing',
            name='polres',
            field=models.ForeignKey(blank=True, help_text='Polres yang upload data preprocessing ini', null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreapp.polres', verbose_name='Polres'),
        ),
        migrations.AlterField(
            model_name='kecelakaanraw',
            name='polres',
            field=models.ForeignKey(blank=True, help_text='Polres yang upload data raw ini', null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreapp.polres', verbose_name='Polres'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='polres',
            field=models.ForeignKey(blank=True, help_text='Polres yang dikelola oleh user ini (dinamis dari database)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreapp.polres', verbose_name='Polres'),
        ),
        migrations.AlterField(
            model_name='ruasjalan',
            name='polres',
            field=models.ForeignKey(blank=True, help_text='Polres yang menambahkan ruas jalan ini', null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreapp.polres', verbose_name='Polres'),
        ),
    ]
