# Generated by Django 6.0.1 on 2026-01-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruasjalan',
            name='lat_akhir',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude titik akhir ruas jalan', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='ruasjalan',
            name='lat_awal',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude titik awal ruas jalan', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='ruasjalan',
            name='lon_akhir',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude titik akhir ruas jalan', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='ruasjalan',
            name='lon_awal',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude titik awal ruas jalan', max_digits=9, null=True),
        ),
    ]
