# Generated by Django 6.0.1 on 2026-05-24 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_profile_is_active_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('kode', models.CharField(help_text='Kode Polres unik (misal: madiun, madiun_kota)', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Polres',
                'ordering': ['nama'],
            },
        ),
        migrations.AddField(
            model_name='kecelakaanpreprosesing',
            name='polres_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kecelakaan_preprosesing_new', to='coreapp.polres'),
        ),
        migrations.AddField(
            model_name='kecelakaanraw',
            name='polres_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kecelakaan_raw_new', to='coreapp.polres'),
        ),
        migrations.AddField(
            model_name='profile',
            name='polres_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_new', to='coreapp.polres'),
        ),
        migrations.AddField(
            model_name='ruasjalan',
            name='polres_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ruas_jalan_new', to='coreapp.polres'),
        ),
    ]
