# Generated by Django 6.0.1 on 2026-05-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_polres_alter_kecelakaanpreprosesing_polres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lakamentah',
            name='tahun',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tahun'),
        ),
    ]
