# Generated by Django 6.0.1 on 2026-02-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_ruasjalan_lat_akhir_ruasjalan_lat_awal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruasjalan',
            name='nama_ruas',
            field=models.CharField(max_length=45),
        ),
    ]
