# Generated by Django 6.0.1 on 2026-02-16 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_alter_ruasjalan_nama_ruas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kecelakaan',
            name='jumlah_kecelakaan',
        ),
    ]
