# Generated by Django 6.0.1 on 2026-05-26 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_lakamentah_tahun'),
    ]

    operations = [
        migrations.AddField(
            model_name='lakamentah',
            name='polres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreapp.polres', verbose_name='Polres'),
        ),
    ]
