# Generated by Django 6.0.1 on 2026-05-29 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_lakamentah_polres'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusterdata',
            name='polres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreapp.polres', verbose_name='Polres'),
        ),
        migrations.AddField(
            model_name='clusterdata',
            name='tahun',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tahun'),
        ),
    ]
