# Generated by Django 6.0.1 on 2026-02-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_remove_kecelakaan_jumlah_kecelakaan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kecelakaan',
            name='latitude',
            field=models.DecimalField(decimal_places=20, max_digits=30),
        ),
        migrations.AlterField(
            model_name='kecelakaan',
            name='longitude',
            field=models.DecimalField(decimal_places=20, max_digits=30),
        ),
    ]
