# Generated by Django 6.0.1 on 2026-02-27 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_kecamatan_kota_kelurahan_kecamatan_kota'),
        ('coreapp', '0005_alter_kecelakaan_latitude_alter_kecelakaan_longitude'),
    ]

    operations = [
    ]
