# Generated by Django 6.0.1 on 2026-06-04 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0005_clusterdata_polres_clusterdata_tahun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='google_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login_at',
        ),
        migrations.AlterField(
            model_name='kecelakaanpreprosesing',
            name='desa',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='kecelakaanpreprosesing',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kecelakaanpreprosesing',
            name='kabupaten_kota',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='kecelakaanpreprosesing',
            name='kecamatan',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='kecelakaanpreprosesing',
            name='nomor_kecelakaan',
            field=models.CharField(blank=True, help_text='Nomor identitas kecelakaan', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='polres',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='polres',
            name='kode',
            field=models.CharField(help_text='Contoh: polres_madiun', max_length=15, unique=True, verbose_name='Kode Polres'),
        ),
        migrations.AlterField(
            model_name='polres',
            name='nama',
            field=models.CharField(max_length=25, verbose_name='Nama Polres'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Jabatan'),
        ),
        migrations.AlterField(
            model_name='ruasjalan',
            name='nama_ruas',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ruasjalan',
            name='wilayah',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='segmenjalan',
            name='nama_segmen',
            field=models.CharField(blank=True, help_text='Nama segmen, bisa diubah dinamis', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='segmenjalan',
            name='titik_akhir',
            field=models.CharField(blank=True, help_text='Label titik akhir (contoh: Titik 2)', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='segmenjalan',
            name='titik_awal',
            field=models.CharField(blank=True, help_text='Label titik awal (contoh: Titik 1)', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=30, unique=True, verbose_name='Email Institusi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=10, verbose_name='Nama Depan'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=10, verbose_name='Nama Belakang'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Nama Lengkap'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Username'),
        ),
    ]
