# Generated by Django 6.0.1 on 2026-06-04 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0006_remove_profile_avatar_remove_profile_institution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruasjalan',
            name='nama_ruas',
            field=models.CharField(max_length=50),
        ),
    ]
