# Generated by Django 6.0.1 on 2026-03-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0006_merge_20260227_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruasjalan',
            name='geometry',
            field=models.TextField(blank=True, help_text='GeoJSON LineString untuk seluruh ruas jalan', null=True),
        ),
        migrations.AddField(
            model_name='segmenjalan',
            name='geometry',
            field=models.TextField(blank=True, help_text='GeoJSON LineString untuk segmen ini', null=True),
        ),
        migrations.AlterField(
            model_name='ruasjalan',
            name='nama_ruas',
            field=models.CharField(max_length=100),
        ),
    ]
