# Generated by Django 6.0.1 on 2026-06-04 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0007_alter_ruasjalan_nama_ruas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Password'),
        ),
    ]
