# Generated by Django 6.0.1 on 2026-03-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0007_ruasjalan_geometry_segmenjalan_geometry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmenjalan',
            name='lat_akhir',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='segmenjalan',
            name='lat_awal',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='segmenjalan',
            name='lon_akhir',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='segmenjalan',
            name='lon_awal',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
