# Generated by Django 6.0.1 on 2026-03-13 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0008_segmenjalan_lat_akhir_segmenjalan_lat_awal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmenjalan',
            name='lat_akhir',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude titik akhir segmen', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='segmenjalan',
            name='lat_awal',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude titik awal segmen', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='segmenjalan',
            name='lon_akhir',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude titik akhir segmen', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='segmenjalan',
            name='lon_awal',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude titik awal segmen', max_digits=9, null=True),
        ),
        migrations.CreateModel(
            name='SegmenTitik',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('urutan', models.IntegerField(help_text='Urutan titik dalam segmen (0 = titik awal)')),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude titik', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude titik', max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('segmen_jalan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titik', to='coreapp.segmenjalan')),
            ],
            options={
                'verbose_name_plural': 'Segmen Titik',
                'ordering': ['segmen_jalan', 'urutan'],
                'unique_together': {('segmen_jalan', 'urutan')},
            },
        ),
    ]
