# Generated by Django 6.0.1 on 2026-06-14 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0008_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50, verbose_name='Nama Polda')),
                ('kode', models.CharField(help_text='Contoh: polda_jatim', max_length=20, unique=True, verbose_name='Kode Polda')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Polda',
                'verbose_name_plural': 'Polda',
                'ordering': ['nama'],
            },
        ),
        migrations.AddField(
            model_name='polres',
            name='polda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polres', to='coreapp.polda', verbose_name='Polda'),
        ),
    ]
