# Generated by Django 6.0.1 on 2026-03-13 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0009_alter_segmenjalan_lat_akhir_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SegmenTitik',
        ),
    ]
