# Generated by Django 6.0.1 on 2026-06-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0009_polda_polres_polda'),
    ]

    operations = [
        migrations.AddField(
            model_name='polda',
            name='alamat',
            field=models.TextField(blank=True, null=True, verbose_name='Alamat'),
        ),
        migrations.AddField(
            model_name='polda',
            name='telepon',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telepon'),
        ),
    ]
