# Generated by Django 6.0.1 on 2026-03-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0010_delete_segmentitik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmenjalan',
            name='lat_akhir',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='segmenjalan',
            name='lat_awal',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='segmenjalan',
            name='lon_akhir',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='segmenjalan',
            name='lon_awal',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
    ]
