# Generated by Django 6.0.1 on 2026-06-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0010_polda_alamat_polda_telepon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kecelakaanpreprosesing',
            name='nomor_kecelakaan',
            field=models.CharField(blank=True, help_text='Nomor identitas kecelakaan', max_length=5, null=True, unique=True),
        ),
    ]
