# Generated by Django 6.0.1 on 2026-03-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0011_alter_segmenjalan_lat_akhir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmenjalan',
            name='titik_akhir',
            field=models.CharField(blank=True, help_text='Label titik akhir (contoh: Titik 2)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='segmenjalan',
            name='titik_awal',
            field=models.CharField(blank=True, help_text='Label titik awal (contoh: Titik 1)', max_length=100, null=True),
        ),
    ]
