# Generated by Django 6.0.1 on 2026-06-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0011_alter_kecelakaanpreprosesing_nomor_kecelakaan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=40, unique=True, verbose_name='Email Institusi'),
        ),
    ]
