# Generated by Django 6.0.1 on 2026-04-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0012_segmenjalan_titik_akhir_segmenjalan_titik_awal'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmenjalan',
            name='keterangan',
            field=models.TextField(blank=True, help_text='Penjelasan/keterangan segmen', null=True),
        ),
        migrations.AddField(
            model_name='segmenjalan',
            name='nama_segmen',
            field=models.CharField(blank=True, help_text='Nama segmen, bisa diubah dinamis', max_length=255, null=True),
        ),
    ]
