# Generated by Django 6.0.1 on 2026-04-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0013_segmenjalan_keterangan_segmenjalan_nama_segmen'),
    ]

    operations = [
        migrations.CreateModel(
            name='KMeansData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_referensi', models.CharField(blank=True, max_length=50, null=True)),
                ('umur', models.IntegerField()),
                ('tkp', models.CharField(max_length=255)),
                ('penyebab', models.CharField(max_length=255)),
                ('hari', models.CharField(max_length=20)),
                ('tanggal', models.DateField()),
                ('jam', models.CharField(max_length=10)),
                ('jenis_kendaraan', models.CharField(max_length=100)),
                ('tipe_kendaraan', models.CharField(max_length=100)),
                ('kerugian_material', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'K-Means Data',
                'ordering': ['-tanggal', '-jam'],
            },
        ),
    ]
