# Generated by Django 6.0.1 on 2026-04-12 17:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0013_segmenjalan_keterangan_segmenjalan_nama_segmen'),
    ]

    operations = [
        migrations.CreateModel(
            name='KecelakaanRaw',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('waktu', models.TimeField()),
                ('latitude', models.DecimalField(decimal_places=20, max_digits=30)),
                ('longitude', models.DecimalField(decimal_places=20, max_digits=30)),
                ('korban_meninggal', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('korban_luka_berat', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('korban_luka_ringan', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('kerugian_materi', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('desa', models.CharField(max_length=100)),
                ('kecamatan', models.CharField(max_length=100)),
                ('kabupaten_kota', models.CharField(max_length=100)),
                ('keterangan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Data Kecelakaan Raw',
                'ordering': ['-tanggal', '-waktu'],
            },
        ),
        migrations.AlterField(
            model_name='kecelakaan',
            name='latitude',
            field=models.DecimalField(decimal_places=20, help_text='Latitude koordinat kecelakaan', max_digits=30),
        ),
        migrations.AlterField(
            model_name='kecelakaan',
            name='longitude',
            field=models.DecimalField(decimal_places=20, help_text='Longitude koordinat kecelakaan', max_digits=30),
        ),
        migrations.AlterField(
            model_name='kecelakaan',
            name='segmen_jalan',
            field=models.ForeignKey(blank=True, help_text='Otomatis diassign ke segmen terdekat (threshold 5km) saat disimpan. Bisa diubah manual jika perlu.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kecelakaan', to='coreapp.segmenjalan'),
        ),
        migrations.CreateModel(
            name='KecelakaanPreprosesing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('waktu', models.TimeField()),
                ('latitude', models.DecimalField(decimal_places=20, max_digits=30)),
                ('longitude', models.DecimalField(decimal_places=20, max_digits=30)),
                ('korban_meninggal', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('korban_luka_berat', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('korban_luka_ringan', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('kerugian_materi', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('desa', models.CharField(max_length=100)),
                ('kecamatan', models.CharField(max_length=100)),
                ('kabupaten_kota', models.CharField(max_length=100)),
                ('keterangan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('segmen_jalan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kecelakaan_preprosesing', to='coreapp.segmenjalan')),
            ],
            options={
                'verbose_name_plural': 'Data Kecelakaan Preprocessing',
                'ordering': ['-tanggal', '-waktu'],
            },
        ),
    ]
