# Generated by Django 6.0.1 on 2026-04-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0014_kecelakaanraw_alter_kecelakaan_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kecelakaanpreprosesing',
            name='nomor_kecelakaan',
            field=models.CharField(blank=True, help_text='Nomor identitas kecelakaan', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='kecelakaanraw',
            name='nomor_kecelakaan',
            field=models.CharField(blank=True, help_text='Nomor identitas kecelakaan', max_length=50, null=True, unique=True),
        ),
    ]
