# Generated by Django 6.0.1 on 2026-04-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0015_kecelakaanpreprosesing_nomor_kecelakaan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kecelakaanpreprosesing',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kecelakaanpreprosesing',
            name='nomor_kecelakaan',
            field=models.CharField(blank=True, help_text='Nomor identitas kecelakaan', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='kecelakaanraw',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='kecelakaanraw',
            name='nomor_kecelakaan',
            field=models.CharField(blank=True, help_text='Nomor identitas kecelakaan', max_length=50, null=True),
        ),
    ]
