# Generated by Django 6.0.1 on 2026-04-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0016_alter_kecelakaanpreprosesing_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruasjalan',
            name='lat_akhir',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='Latitude titik akhir ruas jalan', max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='ruasjalan',
            name='lat_awal',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='Latitude titik awal ruas jalan', max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='ruasjalan',
            name='lon_akhir',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='Longitude titik akhir ruas jalan', max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='ruasjalan',
            name='lon_awal',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='Longitude titik awal ruas jalan', max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='segmenjalan',
            name='lat_akhir',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='segmenjalan',
            name='lat_awal',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='segmenjalan',
            name='lon_akhir',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='segmenjalan',
            name='lon_awal',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True),
        ),
    ]
