# Generated by Django 6.0.1 on 2026-04-28 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0015_aiconfig'),
        ('coreapp', '0017_alter_ruasjalan_lat_akhir_alter_ruasjalan_lat_awal_and_more'),
    ]

    operations = [
    ]
