# Generated by Django 6.0.1 on 2026-04-28 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0018_merge_20260428_1149'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KMeansData',
            new_name='ClusterData',
        ),
        migrations.AlterModelOptions(
            name='clusterdata',
            options={'ordering': ['-tanggal', '-jam'], 'verbose_name_plural': 'Cluster Data'},
        ),
        migrations.AlterModelTable(
            name='clusterdata',
            table='clusterdata',
        ),
    ]
