# Generated by Django 6.0.1 on 2026-05-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0020_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LakaMentah',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('no', models.IntegerField(blank=True, null=True)),
                ('tanggal', models.TextField(blank=True, null=True)),
                ('lap_pol', models.TextField(blank=True, null=True)),
                ('uraian_kejadian', models.TextField(blank=True, null=True)),
                ('tkp', models.TextField(blank=True, null=True)),
                ('terlapor', models.TextField(blank=True, null=True)),
                ('korban', models.TextField(blank=True, null=True)),
                ('bb', models.TextField(blank=True, null=True)),
                ('ket', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Data Laka Mentah',
                'db_table': 'laka_mentah',
                'ordering': ['no'],
            },
        ),
    ]
