# Generated by Django 6.0.1 on 2026-05-19 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0021_lakamentah'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lakamentah',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Data Laka Mentah'},
        ),
        migrations.RemoveField(
            model_name='lakamentah',
            name='no',
        ),
    ]
